spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_login
    username: octouser
    password: passdbmexi1q0p
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

  security:
    oauth2:
      client:
        registration:
#          google:
#            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
#            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - email
#              - profile
          facebook:
            clientId: 312966114129416
            clientSecret: 00d95ef9596c249c07b6f5c4469056c9
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v12.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v12.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v12.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
  #         github:
 #           clientId: d3e47fc2ddd966fa4352
 #           clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
 #           redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
 #           scope:
 #             - user:email
 #             - read:user

  app:
    auth:
      tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
      tokenExpirationMsec: 864000000
    cors:
      allowedOrigins: http://localhost:3000
    oauth2:
      authorizedRedirectUris:
        - http://localhost:3000/oauth2/redirect
        - myandroidapp://oauth2/redirect
        - myiosapp://oauth2/redirect
